export { Home } from './Home'
export { About } from './About'
export { Work } from './Work'
export { Projects } from './Projects'
export { ProjectDetail } from './ProjectDetail'
export { Passions } from './Passions'
